# Generated by Django 4.2.4 on 2023-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Celular',
                'verbose_name_plural': 'Celulares',
                'ordering': ['-modelo'],
            },
        ),
    ]
