# Generated by Django 4.2.4 on 2023-08-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celular',
            options={'ordering': ['-data'], 'verbose_name': 'Celular', 'verbose_name_plural': 'Celulares'},
        ),
        migrations.AddField(
            model_name='celular',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
