# Generated by Django 4.2.4 on 2023-08-24 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_celular_options_celular_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
