# Generated by Django 4.2.4 on 2023-08-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
